name: Thumbnail Uploader

on:
  schedule:
    # Run every week
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  cron:
    name: Thumbnail Uploader
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U requests opencv-python

      - name: execute py script
        run: python main.py

      - name: Update repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Thumbnails Updated"
          git push

      - name: execute py script
        run: python changeGitIgnore.py

      - name: Update repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "GitIgnore Updated"
          git push
